"""02_add_wallet_and_transaction

Revision ID: 68c596afd2b6
Revises: 3729414bd749
Create Date: 2024-09-11 20:21:51.863107

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "68c596afd2b6"
down_revision = "3729414bd749"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wallet",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_uid", sa.UUID(), nullable=False),
        sa.Column("balance", sa.DECIMAL(precision=20, scale=2), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("balance >= 0", name="check_balance_positive"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_wallet_created_at"), "wallet", ["created_at"], unique=False)
    op.create_index(op.f("ix_wallet_user_uid"), "wallet", ["user_uid"], unique=False)
    op.create_table(
        "transaction",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sender_id", sa.UUID(), nullable=False),
        sa.Column("receiver_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.DECIMAL(precision=20, scale=2), nullable=False),
        sa.Column("is_done", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("amount >= 0", name="check_balance_positive"),
        sa.ForeignKeyConstraint(
            ["receiver_id"],
            ["wallet.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["wallet.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_transaction_created_at"), "transaction", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_transaction_receiver_id"), "transaction", ["receiver_id"], unique=False
    )
    op.create_index(op.f("ix_transaction_sender_id"), "transaction", ["sender_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transaction_sender_id"), table_name="transaction")
    op.drop_index(op.f("ix_transaction_receiver_id"), table_name="transaction")
    op.drop_index(op.f("ix_transaction_created_at"), table_name="transaction")
    op.drop_table("transaction")
    op.drop_index(op.f("ix_wallet_user_uid"), table_name="wallet")
    op.drop_index(op.f("ix_wallet_created_at"), table_name="wallet")
    op.drop_table("wallet")
    # ### end Alembic commands ###
