"""03_outbox_events

Revision ID: 726c7cd8c26e
Revises: 68c596afd2b6
Create Date: 2024-09-19 08:57:31.919156

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "726c7cd8c26e"
down_revision = "68c596afd2b6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("topic_name", sa.String(length=254), nullable=False),
        sa.Column("producer", sa.String(length=254), nullable=False),
        sa.Column("body", sa.JSON(), nullable=False),
        sa.Column("status", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_event_created_at"), "event", ["created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_event_created_at"), table_name="event")
    op.drop_table("event")
    # ### end Alembic commands ###
